// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwqpgfnmpoxksqtmbluu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cXBnZm5tcG94a3NxdG1ibHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzkzMTUsImV4cCI6MjA2MTI1NTMxNX0.NATOntKKUXILf4UVIy3nUWIdl--avHP9N1ue9cMaHRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);